# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bwca < Formula
  desc "Bitwarden has created a SERVE mode for the CLI tool, this CLI interacts with that REST API on localhost"
  homepage "https://github.com/maahsome/bwca/"
  version "0.0.11"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maahsome/bwca/releases/download/v0.0.11/bwca_darwin_arm64.tar.gz"
      sha256 "f5825e202a45b0cf5a7ee6a916fe2775e46d7a4e5c2cb138ccabf095f3ae9abb"

      def install
        bin.install "bwca"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maahsome/bwca/releases/download/v0.0.11/bwca_darwin_amd64.tar.gz"
      sha256 "102d8b97c74a122f8fdff3fe5a6a5002bc12d16b0cbfec1070fcdbeb12d3dee0"

      def install
        bin.install "bwca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maahsome/bwca/releases/download/v0.0.11/bwca_linux_arm64.tar.gz"
      sha256 "215dd291a1107a7c2e8b51694c66068da0d854280fa1a760300987f118405704"

      def install
        bin.install "bwca"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maahsome/bwca/releases/download/v0.0.11/bwca_linux_amd64.tar.gz"
      sha256 "78438d92cbb909d3dd46e993710fb054124d268369dd56c5bb52a84613180f18"

      def install
        bin.install "bwca"
      end
    end
  end

  test do
    system "#{bin}/bwca --help"
  end
end
