# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bwca < Formula
  desc "Bitwarden has created a SERVE mode for the CLI tool, this CLI interacts with that REST API on localhost"
  homepage "https://github.com/maahsome/bwca/"
  version "0.0.17"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maahsome/bwca/releases/download/v0.0.17/bwca_darwin_arm64.tar.gz"
      sha256 "e27dd28a91bdc5ea03da9bba1ba59ae9b9718084e30e1b82d99a3e815c193ac5"

      def install
        bin.install "bwca"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maahsome/bwca/releases/download/v0.0.17/bwca_darwin_amd64.tar.gz"
      sha256 "94cc9415ebb0be76ec40ec43e6b5592916247c2e1d5d2f4abca4845aacf674ac"

      def install
        bin.install "bwca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maahsome/bwca/releases/download/v0.0.17/bwca_linux_arm64.tar.gz"
      sha256 "c3bae8deffadf29a2a03f73de4477e30936ee0c9807bbc9842b74fdea5e026f8"

      def install
        bin.install "bwca"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maahsome/bwca/releases/download/v0.0.17/bwca_linux_amd64.tar.gz"
      sha256 "eb91aa98c9ea326b3bb0fc467a71aefa45327e7e4336acd15d247e5df9ba5d5f"

      def install
        bin.install "bwca"
      end
    end
  end

  test do
    system "#{bin}/bwca --help"
  end
end
