# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bwca < Formula
  desc "Bitwarden has created a SERVE mode for the CLI tool, this CLI interacts with that REST API on localhost"
  homepage "https://github.com/maahsome/bwca/"
  version "0.0.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maahsome/bwca/releases/download/v0.0.14/bwca_darwin_amd64.tar.gz"
      sha256 "29cf148cc6f14058b076c84343336aa695c8668ad478574d2897c991d53eca6b"

      def install
        bin.install "bwca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maahsome/bwca/releases/download/v0.0.14/bwca_darwin_arm64.tar.gz"
      sha256 "a317e144e7b6226249a56738984470c9c2db6d0542ca582eb887c75c748e144d"

      def install
        bin.install "bwca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/maahsome/bwca/releases/download/v0.0.14/bwca_linux_amd64.tar.gz"
      sha256 "f25244a1f13449b0e0f8ce476c4a7de5331396734af41ee6bd56be03060e40ad"

      def install
        bin.install "bwca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maahsome/bwca/releases/download/v0.0.14/bwca_linux_arm64.tar.gz"
      sha256 "da2b6ce6e7500b4eca653e4a6fa54f46aa26b647f9bf7f8965e1bfbb64f6d435"

      def install
        bin.install "bwca"
      end
    end
  end

  test do
    system "#{bin}/bwca --help"
  end
end
