# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChangelogPr < Formula
  desc "CLI tool for building changelog from PR descriptions based on a template"
  homepage "https://github.com/maahsome/changelog-pr/"
  version "0.0.3"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/maahsome/changelog-pr/releases/download/v0.0.3/changelog-pr_darwin_amd64.tar.gz"
    sha256 "0aaeeb175e06cb758c15488aba316310bb90e26d3e56b7e32bd6691581a03611"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/maahsome/changelog-pr/releases/download/v0.0.3/changelog-pr_linux_amd64.tar.gz"
    sha256 "3929dcd552a80575f6eeff2557ef60631f50f921ea913fc456c5bc18983c7a02"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/maahsome/changelog-pr/releases/download/v0.0.3/changelog-pr_linux_arm64.tar.gz"
    sha256 "2cc74ae4e2ead266d57b76c95baf85cca0f73544862e6b194873571adf3470dc"
  end

  def install
    bin.install "changelog-pr"
  end

  test do
    system "#{bin}/changelog-pr --help"
  end
end
