# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChangelogPr < Formula
  desc "CLI tool for building changelog from PR descriptions based on a template"
  homepage "https://github.com/Maahsome/changelog-pr/"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Maahsome/changelog-pr/releases/download/v0.2.3/changelog-pr_darwin_amd64.tar.gz"
      sha256 "9518981b2f7ec7a2247e0d0202ccd98437cea1baabdc9ff2354786937ebd547d"

      def install
        bin.install "changelog-pr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Maahsome/changelog-pr/releases/download/v0.2.3/changelog-pr_linux_amd64.tar.gz"
      sha256 "d644631f1b2a69b3e80ad0c6950c32d5d960c8386845f07dae9dece46737dfb4"

      def install
        bin.install "changelog-pr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Maahsome/changelog-pr/releases/download/v0.2.3/changelog-pr_linux_arm64.tar.gz"
      sha256 "23f02094b1986e41766487d94f156228a33afa5219ad0aefe801297fbd8e9d2c"

      def install
        bin.install "changelog-pr"
      end
    end
  end

  test do
    system "#{bin}/changelog-pr --help"
  end
end
