# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabTool < Formula
  desc "CLI tool to reduce reliance on GUI interactions, initially driven by wanting to grep through TRACE output of pipeline jobs"
  homepage "https://github.com/maahsome/gitlab-tool/"
  version "0.0.14"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maahsome/gitlab-tool/releases/download/v0.0.14/gitlab-tool_darwin_arm64.tar.gz"
      sha256 "1fd9354d9dbc062f47a392044b9e0b574adcc21f71265a444534478b885b838f"

      def install
        bin.install "gitlab-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maahsome/gitlab-tool/releases/download/v0.0.14/gitlab-tool_darwin_amd64.tar.gz"
      sha256 "6bbc3d07229d70a457e6c9c9088157bc6d41977bc6491847de4017de7c676b74"

      def install
        bin.install "gitlab-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maahsome/gitlab-tool/releases/download/v0.0.14/gitlab-tool_linux_arm64.tar.gz"
      sha256 "b19e9256c865f2892e82739e91833b23143e64d51e6f31e49512001896481f18"

      def install
        bin.install "gitlab-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maahsome/gitlab-tool/releases/download/v0.0.14/gitlab-tool_linux_amd64.tar.gz"
      sha256 "98719928c10a4fd97a17e36beabffa9a4a9f513676fbeb97ca7a39aa510d4a9f"

      def install
        bin.install "gitlab-tool"
      end
    end
  end

  test do
    system "#{bin}/gitlab-tool --help"
  end
end
