# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabTool < Formula
  desc "CLI tool to reduce reliance on GUI interactions, initially driven by wanting to grep through TRACE output of pipeline jobs"
  homepage "https://github.com/maahsome/gitlab-tool/"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maahsome/gitlab-tool/releases/download/v0.0.8/gitlab-tool_darwin_arm64.tar.gz"
      sha256 "35b4ad3c967cd62654582d23e2011bcbc7354322ea620adaf4cc824f32735c92"

      def install
        bin.install "gitlab-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maahsome/gitlab-tool/releases/download/v0.0.8/gitlab-tool_darwin_amd64.tar.gz"
      sha256 "ba0cb5100c40bf96cf8f51e1de939fb3951de440a344ddef01be67c982dac264"

      def install
        bin.install "gitlab-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/maahsome/gitlab-tool/releases/download/v0.0.8/gitlab-tool_linux_amd64.tar.gz"
      sha256 "f7563aa3d2c90232b24d2c48ecac42464b22f2a0289a2e1dec9cb894a15ac6eb"

      def install
        bin.install "gitlab-tool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maahsome/gitlab-tool/releases/download/v0.0.8/gitlab-tool_linux_arm64.tar.gz"
      sha256 "b8a5417c3a883cf0f99cb49b35b6aa48d83ecf29e1fddd091d3a3e440a2b8075"

      def install
        bin.install "gitlab-tool"
      end
    end
  end

  test do
    system "#{bin}/gitlab-tool --help"
  end
end
