# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IniOp < Formula
  desc "CLI tool for manipulating ini formatted files"
  homepage "https://github.com/maahsome/ini-op/"
  version "0.2.9"

  on_macos do
    url "https://github.com/maahsome/ini-op/releases/download/v0.2.9/ini-op_darwin_amd64.tar.gz"
    sha256 "7839a979e37f1e36e73535a509a65c3ba08de20429d6604088871e2fe039c4ae"

    def install
      bin.install "ini-op"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the IniOp
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maahsome/ini-op/releases/download/v0.2.9/ini-op_linux_arm64.tar.gz"
      sha256 "59d808008948218a8758a019b69256c67facf99681a28151d1c5b5c944479c94"

      def install
        bin.install "ini-op"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maahsome/ini-op/releases/download/v0.2.9/ini-op_linux_amd64.tar.gz"
      sha256 "6fd02d1e74520597eaa1430e14391735165a3f35e3dce9aed3ba085605de8c84"

      def install
        bin.install "ini-op"
      end
    end
  end

  test do
    system "#{bin}/ini-op --help"
  end
end
