# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IniOp < Formula
  desc "CLI tool for manipulating ini formatted files"
  homepage "https://github.com/maahsome/ini-op/"
  version "0.2.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maahsome/ini-op/releases/download/v0.2.9/ini-op_darwin_arm64.tar.gz"
      sha256 "9b04af56f8a58db148460d6c20405f89f470ae3ad058867515cf88fbfbfbb95f"

      def install
        bin.install "ini-op"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maahsome/ini-op/releases/download/v0.2.9/ini-op_darwin_amd64.tar.gz"
      sha256 "e6920a5047066dd2b59125b47805ec80f4b34293fb37ee5afa6be9721d4ddbad"

      def install
        bin.install "ini-op"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/maahsome/ini-op/releases/download/v0.2.9/ini-op_linux_amd64.tar.gz"
      sha256 "b04ec2cca499ef06adb51eeebf37ed347d72988589a0cc6e99525356fa44b30c"

      def install
        bin.install "ini-op"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maahsome/ini-op/releases/download/v0.2.9/ini-op_linux_arm64.tar.gz"
      sha256 "37c8ce5ec746f3653a841080f0e9e145a5e216c6ab9aafc5818bde31f8ddde49"

      def install
        bin.install "ini-op"
      end
    end
  end

  test do
    system "#{bin}/ini-op --help"
  end
end
