# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ktrouble < Formula
  desc "A CLI tool built to help with troubleshooting inside kubernetes"
  homepage "https://github.com/maahsome/ktrouble/"
  version "2.0.2"

  on_macos do
    on_intel do
      url "https://github.com/maahsome/ktrouble/releases/download/v2.0.2/ktrouble_darwin_amd64.tar.gz"
      sha256 "b19b1b5d80bbd26c89c8df9f351fea7fd7163a46bb97a94c266f387d317f7125"

      def install
        bin.install "ktrouble"
      end
    end
    on_arm do
      url "https://github.com/maahsome/ktrouble/releases/download/v2.0.2/ktrouble_darwin_arm64.tar.gz"
      sha256 "7576a192afd909d20d0f1167a284ef49fa02d729332fe67399087b1d69c2ed3f"

      def install
        bin.install "ktrouble"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maahsome/ktrouble/releases/download/v2.0.2/ktrouble_linux_amd64.tar.gz"
        sha256 "7adcd51f514f3b38b5cf2949bdee9d46d616473dbc949b1068199a6375e72bd0"

        def install
          bin.install "ktrouble"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maahsome/ktrouble/releases/download/v2.0.2/ktrouble_linux_arm64.tar.gz"
        sha256 "72f7b51c68baed2db90090b0e4662b6186a6f956cd3fbc308cc2ced69077d736"

        def install
          bin.install "ktrouble"
        end
      end
    end
  end

  test do
    system "#{bin}/ktrouble --help"
  end
end
