# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ktrouble < Formula
  desc "A CLI tool built to help with troubleshooting inside kubernetes"
  homepage "https://github.com/maahsome/ktrouble/"
  version "0.0.26"

  on_macos do
    url "https://github.com/maahsome/ktrouble/releases/download/v0.0.26/ktrouble_darwin_amd64.tar.gz"
    sha256 "aedb76ad1c1672753f9cede28c3754b6e5975e305a176719a08aab911792b326"

    def install
      bin.install "ktrouble"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ktrouble
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maahsome/ktrouble/releases/download/v0.0.26/ktrouble_linux_amd64.tar.gz"
        sha256 "ce9cafcc326170e42eeda07b9a87780aa2ed0c838d739a64471674f66b7656f1"

        def install
          bin.install "ktrouble"
        end
      end
    end
  end

  test do
    system "#{bin}/ktrouble --help"
  end
end
