# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ktrouble < Formula
  desc "A CLI tool built to help with troubleshooting inside kubernetes"
  homepage "https://github.com/maahsome/ktrouble/"
  version "1.0.1"

  on_macos do
    url "https://github.com/maahsome/ktrouble/releases/download/v1.0.1/ktrouble_darwin_amd64.tar.gz"
    sha256 "586f1b51c45e9c49f4de2a7c8b222a7c9bb5e427634db151c8d561830df3c72b"

    def install
      bin.install "ktrouble"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ktrouble
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/maahsome/ktrouble/releases/download/v1.0.1/ktrouble_linux_amd64.tar.gz"
      sha256 "0a585715efe682263febf41b40ae9dce7566351e7a499c4b56c6886f0bebc064"
      def install
        bin.install "ktrouble"
      end
    end
  end

  test do
    system "#{bin}/ktrouble --help"
  end
end
