# This file was generated by GoReleaser. DO NOT EDIT.
class VaultView < Formula
  desc "GoLang TUI cli for browsing Hashicorp Vault secret stores"
  homepage "https://github.com/Maahsome/vault-view"
  version "0.0.5"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Maahsome/vault-view/releases/download/v0.0.5/vault-view-v0.0.5-darwin-amd64.tar.gz"
    sha256 "622753ac45377b5cd80b4a44f58f3f207a9e251ed46ff43fcd29109afba86c1b"
  end
  if OS.linux? && Hardware::CPU.intel?
    if Hardware::CPU.is_32_bit?
      url "https://github.com/Maahsome/vault-view/releases/download/v0.0.5/vault-view-v0.0.5-linux-386.tar.gz"
      sha256 "e6fecd9966abdd6b502fc9b67469b2f5087ca0bd8db7590e81616079782ff272"
    else
      url "https://github.com/Maahsome/vault-view/releases/download/v0.0.5/vault-view-v0.0.5-linux-amd64.tar.gz"
      sha256 "8e476ad2ca130e9c0bf989ba0514132ceacd0ce8d58f4108263f9adedc700111"
    end
  end

  def install
    bin.install "vault-view"
  end

end
