# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VaultView < Formula
  desc "CLI tool with TUI interface used to browse Hashicorp Vault secret stores"
  homepage "https://github.com/maahsome/vault-view/"
  version "0.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/maahsome/vault-view/releases/download/v0.0.6/vault-view_darwin_amd64.tar.gz"
    sha256 "8197712a8b413284173f170293ad3fc7dd2968595e2812694ec89343bb080830"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/maahsome/vault-view/releases/download/v0.0.6/vault-view_linux_amd64.tar.gz"
    sha256 "fc4081335ad135ad35c41ec29baf36d2095c2fda8871356bf72f0926c2a49555"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/maahsome/vault-view/releases/download/v0.0.6/vault-view_linux_arm64.tar.gz"
    sha256 "0a23bcb975b0819803dcac49bbd7eb58520ab89f7af39a5558af2f44cff0cf3d"
  end

  def install
    bin.install "vault-view"
  end

  test do
    system "#{bin}/vault-view --help"
  end
end
